title: "Ken Sadorski | Cybersecurity Analyst"
theme: jekyll-theme-minimal
baseurl: "/"
url: "https://github.com/ksadorski"

# Customization
author: "Ken Sadorski"
social_links:
  - title: "LinkedIn"
    url: "https://linkedin.com/in/ken-sadorski-cyber"
  - title: "GitHub"
    url: "https://github.com/KenSadorski"
  - title: "TryHackMe"
    url: "https://tryhackme.com/r/p/owloperator"
